### PR TITLE
Update to GTK+ 3.20, support HiDPI

### LINKED ISSUE #28: GTK 3.20
GTK 3.20 again broke backwards compatibility for themes. This time they're promising stable naming so I suppose that this might be the last time they break themes. Who knows.

I'm not really up to speed, and I couldn't find a comprehensive list of what changed.
This link promises documented node names, but I can't find them:
https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/

Unless it's the list of defines at the bottom here:
https://developer.gnome.org/gtk3/stable/GtkStyleContext.html
I'm not familiar with GTK theming or GTK at all, so I don't know if that is the relevant information.

P.S.
Everyone contributing to this theme: thank you. It's the one things that makes GTK 3 bearable.

### PR DESCRIPTION
**Pull request by andrewshadura**
This pull request obsoletes PR #19 and PR #31, hopefully also PR #21 and PR #22, and closes #28.

It incorporates work by Andrey Cherepanov (@sibskull) to update the theme to GTK+ 3.20, and rebases a patch by Yuri Khan (@yurivkhan) to support HiDPI.

### CODE REVIEW

**Comment by yurikhan** [comment]
You chose to keep the generated PNG files in the repository?

**Comment by andrewshadura** [comment]
Sure, why not? It’s not like they’re regenerated often or something.

**Comment by yurikhan** [comment]
Well, not a problem if other potential contributors are clearly aware of their “generated-do-not-edit” status.

**Comment by bencaradocdavies** [comment]
Looks fixed in Debian unstable clearlooks-phenix-theme 6.0.3+git20161006-2. Thank you so much @andrewshadura, @sibskull, and @yurikhan for your support of the One True Theme.  :-)

**Comment by jpfleury** [comment]
Thanks all for this work. See new release 7.0 for the support of GTK 3.20.

**Pull request merged**
